### ISSUE TITLE
Unicité de l'artiste

### ISSUE THREAD

**Issue by nyanloutre** [UTBroM/PopCornTheque#18]
Rajouter une contrainte d'unicité du nom et prénom d'un artiste dans Win'Design

**Comment by Vskilet** [comment]
done in script

**Comment by nyanloutre** [comment]
T'es sur de toi ?

**Comment by Vskilet** [comment]
Oui

Le mer. 7 janv. 2015 01:23, Paul TREHIOU <notifications@github.com> a
écrit :
