### ISSUE TITLE
/!\ Qui a mis un varchar pour la disponibilité du support !!

### ISSUE THREAD

**Issue by nyanloutre** [UTBroM/PopCornTheque#24]
Modifié en Bool dans ma base

A répercuter sur Win'Design

**Comment by Vskilet** [comment]
C'est moi parce que c'est ce que renvoie PHP je vais remettre varchar sinon faut faire un if relou

**Comment by nyanloutre** [comment]
non c'est pas relou
c'est du binaire
Le Tue Jan 06 2015 at 10:08:36, Victor SENE <notifications@github.com> a
écrit :
